Ensure any previous ZFS/SPL modules are removed before loading
new ZFS/SPL modules to ensure correct drivers are being tested.
Changes in debian/tests/kernel-smoke-test

Gbp-Dch: Full

diff --git a/debian/tests/kernel-smoke-test b/debian/tests/kernel-smoke-test
--- a/debian/tests/kernel-smoke-test
+++ b/debian/tests/kernel-smoke-test
@@ -26,6 +26,9 @@
 # the cumulative testing of each scenario does to the
 # environment.
 #
+LSMOD=/sbin/lsmod
+RMMOD=/sbin/rmmod
+MODPROBE=/sbin/modprobe
 TESTS="kernel-smoke-test-pool-2x2-mirror kernel-smoke-test-pool-4x1-mirror kernel-smoke-test-pool-nested-raidz3 kernel-smoke-test-pool-raidz1 kernel-smoke-test-pool-raidz2 kernel-smoke-test-pool-raidz3 kernel-smoke-test-pool-striped kernel-smoke-test-zil kernel-smoke-test-filesystem kernel-smoke-test-snapshot kernel-smoke-test-clone kernel-smoke-test-send-receive kernel-smoke-test-scrub kernel-smoke-test-encryption"
 rc=0
 #
@@ -38,8 +41,63 @@ then
 	exit 0
 fi
 
+#
+#  Remove a module if it is loaded
+#
+rm_mod()
+{
+	loaded=$($LSMOD | grep "^$1")
+	if [ ! -z "$loaded" ]; then
+		echo "Unloading $1"
+		$RMMOD $1
+	fi
+}
+
+#
+#  Recursively find module dependencies and remove these modules
+#
+rm_mod_dep()
+(
+	mod=$1
+	n=0
+	deps=""
+
+	while true
+	do
+		deps=$($LSMOD | grep "^$mod" | awk '{ print $4 }' | tr ',' ' ')
+		if [ -z "$deps" ]; then
+			rm_mod $mod
+			return 0
+		else
+			for dep in $deps
+			do
+				rm_mod_dep $dep
+				if [ $? -ne 0 ]; then
+					return 1
+				fi
+			done
+		fi
+		n=$((n + 1))
+		if [ $n -gt 20 ]; then
+			echo "Cannot remove $mod or a dependency module $deps"
+			return 1
+		fi
+	done
+	return 0
+)
+
+#
+#  need to stop zed to remove previous zfs
+#
+systemctl stop zfs-zed.service
+
+echo "Removing existing zfs modules"
+rm_mod_dep zfs
+rm_mod_dep spl
+
 # Load zfs kernel module before tests
-/sbin/modprobe zfs
+echo "Loading new zfs modules"
+$MODPROBE zfs
 
 for t in ${TESTS}
 do
