0.8.4-2 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/patches/4000-zsys-support.patch b/debian/patches/4000-zsys-support.patch
--- a/debian/patches/4000-zsys-support.patch
+++ b/debian/patches/4000-zsys-support.patch
@@ -8,11 +8,203 @@ Description: Support zsys systems
 Author: Jean-Baptiste Lallement <jean.baptiste@ubuntu.com>
         Didier Roche <didrocks@ubuntu.com>
 Last-Update: 2019-06-06
-Index: zfs-linux-0.8.3/contrib/initramfs/scripts/zfs.in
+Index: zfs-linux-0.8.4/etc/systemd/system-generators/zfs-mount-generator.in
 ===================================================================
---- zfs-linux-0.8.3.orig/contrib/initramfs/scripts/zfs.in
-+++ zfs-linux-0.8.3/contrib/initramfs/scripts/zfs.in
-@@ -71,6 +71,20 @@ get_fs_value()
+--- zfs-linux-0.8.4.orig/etc/systemd/system-generators/zfs-mount-generator.in
++++ zfs-linux-0.8.4/etc/systemd/system-generators/zfs-mount-generator.in
+@@ -29,6 +29,8 @@ FSLIST="@sysconfdir@/zfs/zfs-list.cache"
+ 
+ [ -d "${FSLIST}" ] || exit 0
+ 
++OLD_IFS=$IFS
++
+ do_fail() {
+   printf 'zfs-mount-generator: %s\n' "$*" > /dev/kmsg
+   exit 1
+@@ -120,6 +122,9 @@ process_line() {
+   requiredby=""
+   noauto="off"
+ 
++  # Escape the mountpoint per systemd policy.
++  mountfile="$(systemd-escape --path --suffix=mount "${p_mountpoint}")"
++
+   if [ -n "${p_systemd_after}" ] && \
+       [ "${p_systemd_after}" != "-" ] ; then
+     after="${p_systemd_after} ${after}"
+@@ -145,6 +150,62 @@ process_line() {
+       [ "${p_encroot}" != "-" ] ; then
+     keyloadunit="zfs-load-key-$(systemd-escape "${p_encroot}").service"
+     if [ "${p_encroot}" = "${dataset}" ] ; then
++
++      # Automount and unmount ZSys USERDATA datasets with keystore
++      zsys_automount=0
++      automount_loadkey_extra_args=""
++      automount_pool=""
++      automount_user=""
++      if echo "${dataset}" | grep -q '/USERDATA/'; then
++        automount_pool=${dataset%%/*}
++        automount_user=${dataset##*/}
++        # Only operate on user dataset mountpoint itself and not its children
++        if ! echo "${automount_user}" | grep -q '/'; then
++          automount_user=${automount_user%%_*}
++          # Ensure we have a keystore
++          if [ -f "/run/keystore/${automount_pool}/${automount_user}.enc" -a -x /usr/sbin/user_keystore ]; then
++            zsys_automount=1
++          fi
++        fi
++      fi
++
++      # Create automount unit and keystore tracker
++      if [ ${zsys_automount} -eq 1 ]; then
++        automountunit="$(systemd-escape --path --suffix=automount "${p_mountpoint}")"
++      echo \
++"# Automatically generated by zfs-mount-generator
++
++[Unit]
++Description=Automount ZFS user home for ${dataset} on demand
++
++[Automount]
++Where=${p_mountpoint}
++TimeoutIdleSec=10
++
++[Install]
++WantedBy=local-fs.target
++"   > "${dest_norm}/${automountunit}"
++        create_dependencies "${automountunit}" "wants" "local-fs.target"
++
++        keystoreunit="zfs-keystore-$(systemd-escape "${p_encroot}").service"
++        automount_loadkey_extra_args="BindsTo=${mountfile}
++BindsTo=${keystoreunit}
++After=${keystoreunit}"
++        echo \
++"# Automatically generated by zfs-mount-generator
++
++[Unit]
++Description=Make available ZFS encryption key for ${dataset} from keystore
++ConditionPathExists=/run/keystore/${automount_pool}/${automount_user}.enc
++BindsTo=${keyloadunit}
++
++[Service]
++Type=oneshot
++RemainAfterExit=yes
++ExecStop=/usr/sbin/user_keystore lock ${automount_pool} ${automount_user}
++"   > "${dest_norm}/${keystoreunit}"
++      fi
++
+       keymountdep=""
+       if [ "${p_keyloc%%://*}" = "file" ] ; then
+         if [ -n "${requiredmounts}" ] ; then
+@@ -200,6 +261,7 @@ Wants=${wants}
+ After=${after}
+ ${requires}
+ ${keymountdep}
++${automount_loadkey_extra_args}
+ 
+ [Service]
+ Type=oneshot
+@@ -248,9 +310,6 @@ ExecStop=${keyunloadcmd}"   > "${dest_no
+     do_fail "invalid mountpoint for ${dataset}"
+   fi
+ 
+-  # Escape the mountpoint per systemd policy.
+-  mountfile="$(systemd-escape --path --suffix=mount "${p_mountpoint}")"
+-
+   # Parse options
+   # see lib/libzfs/libzfs_mount.c:zfs_add_options
+   opts=""
+@@ -437,6 +496,87 @@ Options=defaults${opts},zfsutil" > "${de
+ 
+ }
+ 
++ZPOOL_CACHE="@sysconfdir@/zfs/zpool.cache"
++PROPS="name,mountpoint,canmount,atime,relatime,devices,exec\
++,readonly,setuid,nbmand,encroot,keylocation\
++,org.openzfs.systemd:requires,org.openzfs.systemd:requires-mounts-for\
++,org.openzfs.systemd:before,org.openzfs.systemd:after\
++,org.openzfs.systemd:wanted-by,org.openzfs.systemd:required-by\
++,org.openzfs.systemd:nofail,org.openzfs.systemd:ignore"
++zsys_revert_failed=0
++errfile="/tmp/zsys-revert-out.log"
++
++drop_emergency_on_failure() {
++  if [ ${zsys_revert_failed} -eq 0 ]; then
++    return
++  fi
++
++  # Drop to emergency target in case of failure after cleanup fstab mountpoints.
++  # This avoids booting and having a mix of old and new datasets, and creating directory in the wrong
++  # datasets, like /boot/grub in / which will prevent zfs to mount /boot dataset later on.
++  rm -f "${dest_norm}"/*.mount
++  ln -s /lib/systemd/system/emergency.target "${dest_norm}"/default.target
++
++  printf 'ERROR: zfs-mount-generator failed and you requested a revert:\n' > /dev/kmsg
++  cat "${errfile}" > /dev/kmsg
++  printf 'You can reboot on current master dataset to fix the issue\n' > /dev/kmsg
++}
++
++# Handle revert so that zsys prepares all datasets as expected.
++initzsys() {
++  if [ ! -x @sbindir@/zsysd ]; then
++    return
++  fi
++
++  # Non ZFS system
++  if ! grep -q "root=ZFS=" /proc/cmdline; then
++    return
++  fi
++
++  # If we boot on the same dataset than last time, assume we don’t need to do anything as the cache file will only
++  # import desired pools.
++  bootds="$(sed -e 's/.*root=ZFS=\([^ ]\+\).*/\1/' /proc/cmdline)"
++  if grep -Eq "${bootds}\s+/\s+on" "${FSLIST}/"*; then
++      return
++  fi
++
++  # If we get here: we are reverting. Let zsys handle it
++  trap drop_emergency_on_failure EXIT INT QUIT ABRT PIPE TERM
++
++  exec 3>&1 1>"${errfile}"
++  exec 4>&2 2>&1
++
++  zsys_revert_failed=1
++  # Import and list previously imported pools for zsys
++  if [ -f "${ZPOOL_CACHE}" ]; then
++    @sbindir@/zpool import -c "${ZPOOL_CACHE}" -aN
++  # As a best effort, import all available pools, hoping there is no conflict.
++  else
++    echo "We had to search for all available pools because ${ZPOOL_CACHE} doesn't exist. To avoid this, create a zpool cache file."
++    @sbindir@/zpool import -aN
++  fi
++
++  @sbindir@/zsysd boot-prepare >"${errfile}"
++
++  # If FSLIST is empty, populate with all imported pools
++  if [ -z "$(ls -A ${FSLIST})" ]; then
++    @sbindir@/zpool list -H -o name | xargs -I{} touch ${FSLIST}/{}
++  fi
++
++  # Refresh zfs list cache
++  for cachefile in "${FSLIST}/"* ; do
++    pool=`basename ${cachefile}`
++    @sbindir@/zfs list -H -t filesystem -o "${PROPS}" -r "${pool}" >"${cachefile}"
++  done
++
++  exec 1>&3 3>&-
++  exec 2>&4 4>&-
++  zsys_revert_failed=0
++  rm "${errfile}"
++}
++
++initzsys
++
+ for cachefile in "${FSLIST}/"* ; do
+   # Sort cachefile's lines by canmount, "on" before "noauto"
+   # and feed each line into process_line
+Index: zfs-linux-0.8.4/contrib/initramfs/scripts/zfs
+===================================================================
+--- zfs-linux-0.8.4.orig/contrib/initramfs/scripts/zfs
++++ zfs-linux-0.8.4/contrib/initramfs/scripts/zfs
+@@ -63,6 +63,20 @@ get_fs_value()
  	"${ZFS}" get -H -ovalue $value "$fs" 2> /dev/null
  }
  
@@ -33,7 +225,7 @@ Index: zfs-linux-0.8.3/contrib/initramfs/scripts/zfs.in
  # Find the 'bootfs' property on pool $1.
  # If the property does not contain '/', then ignore this
  # pool by exporting it again.
-@@ -495,16 +509,17 @@ clone_snap()
+@@ -487,16 +501,17 @@ clone_snap()
  	local snap="$1"
  	local destfs="$2"
  	local mountpoint="$3"
@@ -57,7 +249,7 @@ Index: zfs-linux-0.8.3/contrib/initramfs/scripts/zfs.in
  	ZFS_CMD="${ZFS_CMD} $snap $destfs"
  	ZFS_STDERR="$(${ZFS_CMD} 2>&1)"
  	ZFS_ERROR="$?"
-@@ -616,6 +631,15 @@ setup_snapshot_booting()
+@@ -608,6 +623,15 @@ setup_snapshot_booting()
  	snapname="${snap##*@}"
  	ZFS_BOOTFS="${rootfs}_${snapname}"
  
@@ -73,7 +265,7 @@ Index: zfs-linux-0.8.3/contrib/initramfs/scripts/zfs.in
  	if ! grep -qiE '(^|[^\\](\\\\)* )(rollback)=(on|yes|1)( |$)' /proc/cmdline
  	then
  		# If the destination dataset for the clone
-@@ -645,10 +669,18 @@ setup_snapshot_booting()
+@@ -637,10 +661,18 @@ setup_snapshot_booting()
  			#       rpool/ROOT/debian/boot@snap2	=> rpool/ROOT/debian_snap2/boot
  			#       rpool/ROOT/debian/usr@snap2	=> rpool/ROOT/debian_snap2/usr
  			#       rpool/ROOT/debian/var@snap2	=> rpool/ROOT/debian_snap2/var
@@ -92,7 +284,7 @@ Index: zfs-linux-0.8.3/contrib/initramfs/scripts/zfs.in
  			[ -n "$subfs" ] && destfs="${destfs}$subfs" # + sub fs.
  
  			# Get the mountpoint of the filesystem, to be used
-@@ -665,9 +697,38 @@ setup_snapshot_booting()
+@@ -657,9 +689,38 @@ setup_snapshot_booting()
  				fi
  			fi
  
@@ -132,7 +324,46 @@ Index: zfs-linux-0.8.3/contrib/initramfs/scripts/zfs.in
  			    retval=$((retval + 1))
  		fi
  	done
-@@ -930,6 +991,8 @@ mountroot()
+@@ -879,6 +940,38 @@ mountroot()
+ 		shell
+ 	fi
+ 
++	# ------------
++	# Open and mount luks keystore for any pools using one
++	CRYPTROOT=/scripts/local-top/cryptroot
++	# We already processed original crypttab by calling local-top. Only add zvol related ones now.
++	if [ -x "${CRYPTROOT}" ]; then
++	        TABFILE=/cryptroot/crypttab
++	        :>"${TABFILE}"
++		# Wait for all keystore devices in /dev/zvol to appear with a 5s timeout
++		timeout=50
++		NUMKS=$(zfs list -H -o name | grep '/keystore$' | wc -l)
++		while [ ${NUMKS} -ne $(find /dev/zvol/ -name 'keystore' | wc -l) ]; do
++			if [ $timeout -le 0 ]; then
++				break
++			fi
++			sleep .1
++			timeout=$((timeout - 1))
++		done
++		# Locate, then mount the keystore volumes
++		for ks in $(find /dev/zvol/ -name 'keystore'); do
++			[ ! -e "${ks}" ] && continue
++			pool="$(basename $(dirname ${ks}))"
++			echo "keystore-${pool} ${ks} none luks,discard" >> "${TABFILE}"
++		done
++		${CRYPTROOT}
++		for dev in $(find /dev/mapper -name 'keystore-*'); do
++			# Translate filename to path
++			storepath="/run/$(echo $(basename ${dev})|sed -e 's,-,/,')"
++			mkdir -p "${storepath}"
++			mount "${dev}" "${storepath}"
++		done
++	fi
++
+ 	# In case the pool was specified as guid, resolve guid to name
+ 	pool="$("${ZPOOL}" get name,guid -o name,value -H | \
+ 	    awk -v pool="${ZFS_RPOOL}" '$2 == pool { print $1 }')"
+@@ -922,6 +1015,8 @@ mountroot()
  		# Booting from a snapshot?
  		# Will overwrite the ZFS_BOOTFS variable like so:
  		#   rpool/ROOT/debian@snap2 => rpool/ROOT/debian_snap2
@@ -141,7 +372,7 @@ Index: zfs-linux-0.8.3/contrib/initramfs/scripts/zfs.in
  		echo "${ZFS_BOOTFS}" | grep -q '@' && \
  		    setup_snapshot_booting "${ZFS_BOOTFS}"
  	fi
-@@ -967,8 +1030,16 @@ mountroot()
+@@ -959,8 +1054,16 @@ mountroot()
  	# Go through the complete list (recursively) of all filesystems below
  	# the real root dataset
  	filesystems=$("${ZFS}" list -oname -tfilesystem -H -r "${ZFS_BOOTFS}")
@@ -158,7 +389,7 @@ Index: zfs-linux-0.8.3/contrib/initramfs/scripts/zfs.in
  		mount_fs "$fs"
  	done
  
-@@ -1007,3 +1078,8 @@ mountroot()
+@@ -999,3 +1102,8 @@ mountroot()
  		[ "$quiet" != "y" ] && zfs_log_end_msg
  	fi
  }
@@ -167,72 +398,3 @@ Index: zfs-linux-0.8.3/contrib/initramfs/scripts/zfs.in
 +{
 +	dd if=/dev/urandom of=/dev/stdout bs=1 count=100 2>/dev/null | tr -dc 'a-z0-9' | cut -c-6
 +}
-Index: zfs-linux-0.8.3/etc/systemd/system-generators/zfs-mount-generator.in
-===================================================================
---- zfs-linux-0.8.3.orig/etc/systemd/system-generators/zfs-mount-generator.in
-+++ zfs-linux-0.8.3/etc/systemd/system-generators/zfs-mount-generator.in
-@@ -28,6 +28,8 @@ FSLIST="@sysconfdir@/zfs/zfs-list.cache"
- 
- [ -d "${FSLIST}" ] || exit 0
- 
-+OLD_IFS=$IFS
-+
- do_fail() {
-   printf 'zfs-mount-generator: %s\n' "$*" > /dev/kmsg
-   exit 1
-@@ -256,6 +258,55 @@ EOF
-   ln -s "../${mountfile}" "${req_dir}"
- }
- 
-+ZSYS="@sbindir@/zsysd"
-+ZFS="@sbindir@/zfs"
-+ZPOOL="@sbindir@/zpool"
-+initial_pools=""
-+fs_pools=""
-+all_pools=""
-+on_exit() {
-+    # Restore initial zpool import state
-+    IFS=$OLD_IFS
-+    for pool in ${all_pools}; do
-+        if echo "${initial_pools}" | grep -wq "${pool}"; then
-+            continue
-+        fi
-+        if echo "${fs_pools}" | grep -wq "${pool}"; then
-+            continue
-+        fi
-+        zpool export "${pool}"
-+    done
-+}
-+
-+# TODO: we should move that in its own script, and use a systemd service as a fallback.
-+# We need to condition this on current vs previous dataset (across the whole system), so
-+# in /boot.
-+# We will also recall the zedlet directly and regenerate the files if any changes were
-+# made.
-+initzsys() {
-+  if [ ! -x "${ZSYS}" ]; then
-+    return
-+  fi
-+  trap on_exit EXIT INT QUIT ABRT PIPE TERM
-+
-+  # import and list pools for zsys
-+  initial_pools="$(${ZPOOL} list | awk '{if (NR>1) print $1}')"
-+  ${ZPOOL} import -f -a -N -o cachefile=none 2>/dev/null
-+  all_pools="$(zpool list | awk '{if (NR>1) print $1}')"
-+  ${ZSYS} boot-prepare
-+
-+  PROPS="name,mountpoint,canmount,atime,relatime,devices,exec,readonly"
-+  PROPS="${PROPS},setuid,nbmand"
-+
-+  for cachefile in "${FSLIST}/"* ; do
-+    pool=`basename $cachefile`
-+    fs_pools="${fs_pools} ${pool}"
-+    ${ZFS} list -H -t filesystem -o $PROPS -r "${pool}" > "${cachefile}"
-+  done
-+}
-+
-+initzsys
-+
- # Feed each line into process_line
- for cachefile in "${FSLIST}/"* ; do
-   while read -r fs ; do
