0.8.0~rc4-1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/etc/init.d/zfs-functions.in b/etc/init.d/zfs-functions.in
--- a/etc/init.d/zfs-functions.in
+++ b/etc/init.d/zfs-functions.in
@@ -393,6 +393,8 @@ read_fstab()
 	i=0
 	while read -r fs mntpnt fstype opts; do
 		echo "$fs" | egrep -qE '^#|^$' && continue
+		echo "$mntpnt" | egrep -qE '^none|^swap' && continue
+		echo "$fstype" | egrep -qE '^swap' && continue
 
 		if echo "$fs $mntpnt $fstype $opts" | grep -qE "$match"; then
 			eval export FSTAB_dev_$i="$fs"
@@ -421,9 +423,14 @@ is_mounted()
 	mount | \
 	    while read line; do
 		if echo "$line" | grep -q " on $mntpt "; then
-		    return 0
+		    # returns:
+		    #   0 on unsuccessful match
+		    #   1 on a successful match
+		    return 1
 		fi
 	    done
 
-	return 1
+	# The negation will flip the subshell return result where the default
+	# return value is 0 when a match is not found.
+	return $(( !$? ))
 }
