0.8.2-3 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/zfsutils-linux.postinst b/debian/zfsutils-linux.postinst
--- a/debian/zfsutils-linux.postinst
+++ b/debian/zfsutils-linux.postinst
@@ -15,5 +15,13 @@ if [ ! -f /etc/hostid ] || [ "$(stat -c %s /etc/hostid)" -lt 4 ] ; then
 	zgenhostid
 fi
 
+# When processed to here but zfs kernel module is not loaded, the subsequent
+# services would fail to start. In this case the installation process just
+# fails at the postinst stage. The user could do
+#   $ sudo modprobe zfs; sudo dpkg --configure -a
+# to complete the installation.
+#
+modprobe -v zfs || true # modprobe zfs does nothing if zfs.ko was already loaded.
+
 #DEBHELPER#
 
